### ISSUE TITLE
website not reachable via Tor Browser

### ISSUE THREAD

**Issue by mdik** [QubesOS/qubesos.github.io#1]
Hi,

you are behind CloudFlare which censors Tor. You could try reducing your CloudFlare security settings as described on https://support.cloudflare.com/hc/en-us/articles/200170096-How-do-I-turn-the-CloudFlare-captcha-challenge-page-off-

Thanks in advance and kind regards,

Malte

**Comment by marmarek** [comment]
It is already set to "Essentially Off"... I've just checked - there is
no captcha when accessing the website over tor. According to page you've
linked "The setting will only challenge the most threatening visitors to
your site based on their threat score", so maybe there was some abuse
from the exit node you are currently using?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by mdik** [comment]
Ok. It took me three circuits to get through.

Could you host without CloudFlareß

**Comment by marmarek** [comment]
No, we could not. We want to focus on developing Qubes, rather than
configuring servers, and all the protections against DoS attacks.

Anyway as the website is yekyll-based, avilable in public git, it is
straightforward to run own mirror. AFAIR someone is hosting one as tor
service, but I don't have an address handy.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by axon-qubes** [comment]
http://qubesosmamapaxpa.onion/
